language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: /bin/true
script: mvn -B -e clean install
notifications:
  email:
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: never